#!/usr/bin/env bash
# Note: you may need to set SHELLOPTS to include 'igncr' before running this script.
# https://stackoverflow.com/a/17043716/4077294

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
STAGE2_PY=$(cygpath -w "$SCRIPT_DIR/stage2.py")

case "$(uname -s)" in
    CYGWIN*) ;;
    *)       echo "This script is only meant for Cygwin." 2>&1; exit 1 ;;
esac

# 2014-2017
for y in {2014..2017}; do
    for m in {1..9}; do
        cmd /c "python $STAGE2_PY stage2.0$m.$y.csv .am -d --amend" 2>&1 | tee output-0$m-$y.log
    done
    for m in {10..12}; do
        cmd /c "python $STAGE2_PY stage2.$m.$y.csv .am -d --amend" 2>&1 | tee output-$m-$y.log
    done
done

# 2018 (we only have data from Jan-Mar)
for m in {1..3}; do
    cmd /c "python $STAGE2_PY stage2.0$m.$y.csv .am -d --amend" 2>&1 | tee output-0$m-$y.log
done

# 2013 doesn't need any amending since it doesn't have any incident_url_fields_missing instances.

# Update all csvs we successfully amended (i.e. those without incident_url_fields_missing = True).
for am in "$(grep -rL ',True,' --include='*\.am' .)"; do
    csv="${am:2:-3}" # Note: :2 is because grep prepends an extra './'
    mv "$am" "$csv"
done
